### ISSUE TITLE
`LLVMBuildGEP: symbol not found` error

### ISSUE THREAD

**Issue by yahonda** [docker-library/postgres#1080]
Thank you for providing the PostgreSQL docker image. Ruby on Rails is making use of `postgres:alpine` docker image to run its own CI.

Recently, it started failing https://buildkite.com/rails/rails/builds/96360#01880ded-cecb-4a71-9e9f-35db4f5bbce7

Although this is not minimal, here is the steps to reproduce.

- Steps to reproduce

```
git clone -b 7-0-stable https://github.com/rails/rails
cd rails
git clone https://github.com/rails/buildkite-config .buildkite/

RUBY_IMAGE=ruby:3.2 docker-compose -f .buildkite/docker-compose.yml build base
CI=1 POSTGRES_IMAGE=postgres:alpine docker-compose -f .buildkite/docker-compose.yml run postgresdb runner activerecord 'rake db:postgresql:rebuild test:postgresql'
```

- Expected result
It should finish without run.

- Actual result
It raises this error.

```ruby
---
....................................................E

Error:
ActiveRecord::TooManyOrTest#test_too_many_or:
RuntimeError: Wrapped undumpable exception for: ActiveRecord::StatementInvalid: PG::UndefinedFile: ERROR:  could not load library "/usr/local/lib/postgresql/llvmjit.so": Error relocating /usr/local/lib/postgresql/llvmjit.so: LLVMBuildGEP: symbol not found

    /rails/activerecord/lib/active_record/connection_adapters/postgresql_adapter.rb:768:in `exec_params'
    /rails/activerecord/lib/active_record/connection_adapters/postgresql_adapter.rb:768:in `block (2 levels) in exec_no_cache'
    /rails/activesupport/lib/active_support/concurrency/share_lock.rb:187:in `yield_shares'
    /rails/activesupport/lib/active_support/dependencies/interlock.rb:41:in `permit_concurrent_loads'
    /rails/activerecord/lib/active_record/connection_adapters/postgresql_adapter.rb:767:in `block in exec_no_cache'
    /rails/activesupport/lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `handle_interrupt'
    /rails/activesupport/lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `block in synchronize'
    /rails/activesupport/lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `handle_interrupt'
    /rails/activesupport/lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `synchronize'
    /rails/activerecord/lib/active_record/connection_adapters/abstract_adapter.rb:769:in `block in log'
    /rails/activesupport/lib/active_support/notifications/instrumenter.rb:24:in `instrument'
    /rails/activerecord/lib/active_record/connection_adapters/abstract_adapter.rb:760:in `log'
    /rails/activerecord/lib/active_record/connection_adapters/postgresql_adapter.rb:766:in `exec_no_cache'
    /rails/activerecord/lib/active_record/connection_adapters/postgresql_adapter.rb:745:in `execute_and_clear'
    /rails/activerecord/lib/active_record/connection_adapters/postgresql/database_statements.rb:54:in `exec_query'
    /rails/activerecord/lib/active_record/connection_adapters/abstract/database_statements.rb:560:in `select'
    /rails/activerecord/lib/active_record/connection_adapters/abstract/database_statements.rb:66:in `select_all'
    /rails/activerecord/lib/active_record/connection_adapters/abstract/query_cache.rb:110:in `select_all'
    /rails/activerecord/lib/active_record/relation/calculations.rb:358:in `block in execute_simple_calculation'
    /rails/activerecord/lib/active_record/relation.rb:962:in `skip_query_cache_if_necessary'
    /rails/activerecord/lib/active_record/relation/calculations.rb:358:in `execute_simple_calculation'
    /rails/activerecord/lib/active_record/relation/calculations.rb:319:in `perform_calculation'
    /rails/activerecord/lib/active_record/relation/calculations.rb:194:in `calculate'
    /rails/activerecord/lib/active_record/relation/calculations.rb:92:in `count'
    /rails/activerecord/test/cases/relation/or_test.rb:190:in `test_too_many_or'


rails test rails/activerecord/test/cases/relation/or_test.rb:185

**Comment by ImreSamu** [comment]
Hi yahonda!

Probably the same issue:  https://github.com/docker-library/postgres/issues/1076
Fix in progress ( and merged ) : https://github.com/docker-library/postgres/pull/1077

Likely, the new images will be available in a few hours.

**Comment by yahonda** [comment]
Thanks for the update. Will see if the next build addresses the error.

**Comment by yahonda** [comment]
Thanks for the update and fix.

CI is back to green now.
https://buildkite.com/rails/rails/builds/96406#01881602-9147-46fa-9ee5-9734482ca444
