### ISSUE TITLE
Cannot connect to the database from initdb.d script

### ISSUE THREAD

**Issue by synthecypher** [docker-library/postgres#366]
I cannot run migrations as part of my `docker-entrypoint-initdb.d` scripts and they communicate through a port. However, I've found out when these scripts run the database is not yet listening on its port.

```
/usr/local/bin/docker-entrypoint.sh: running /docker-entrypoint-initdb.d/create-schema.sh
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/SQLAlchemy-1.2.0b3-py3.4-linux-x86_64.egg/sqlalchemy/engine/base.py", line 2158, in _wrap_pool_connect
    return fn()
  File "/usr/local/lib/python3.4/dist-packages/SQLAlchemy-1.2.0b3-py3.4-linux-x86_64.egg/sqlalchemy/pool.py", line 344, in unique_connection
    return _ConnectionFairy._checkout(self)
  File "/usr/local/lib/python3.4/dist-packages/SQLAlchemy-1.2.0b3-py3.4-linux-x86_64.egg/sqlalchemy/pool.py", line 781, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/usr/local/lib/python3.4/dist-packages/SQLAlchemy-1.2.0b3-py3.4-linux-x86_64.egg/sqlalchemy/pool.py", line 531, in checkout
    rec = pool._do_get()
  File "/usr/local/lib/python3.4/dist-packages/SQLAlchemy-1.2.0b3-py3.4-linux-x86_64.egg/sqlalchemy/pool.py", line 1276, in _do_get
    return self._create_connection()
  File "/usr/local/lib/python3.4/dist-packages/SQLAlchemy-1.2.0b3-py3.4-linux-x86_64.egg/sqlalchemy/pool.py", line 349, in _create_connection
    return _ConnectionRecord(self)
  File "/usr/local/lib/python3.4/dist-packages/SQLAlchemy-1.2.0b3-py3.4-linux-x86_64.egg/sqlalchemy/pool.py", line 476, in __init__
    self.__connect(first_connect_check=True)
  File "/usr/local/lib/python3.4/dist-packages/SQLAlchemy-1.2.0b3-py3.4-linux-x86_64.egg/sqlalchemy/pool.py", line 666, in __connect
    connection = pool._invoke_creator(self)
  File "/usr/local/lib/python3.4/dist-packages/SQLAlchemy-1.2.0b3-py3.4-linux-x86_64.egg/sqlalchemy/engine/strategies.py", line 105, in connect
    return dialect.connect(*cargs, **cparams)
  File "/usr/local/lib/python3.4/dist-packages/SQLAlchemy-1.2.0b3-py3.4-linux-x86_64.egg/sqlalchemy/engine/default.py", line 410, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/usr/local/lib/python3.4/dist-packages/psycopg2-2.7.3.2-py3.4-linux-x86_64.egg/psycopg2/__init__.py", line 130, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: could not connect to server: Connection refused
  Is the server running on host "localhost" (127.0.0.1) and accepting
  TCP/IP connections on port 7734?
could not connect to server: Cannot assign requested address
  Is the server running on host "localhost" (::1) and accepting
  TCP/IP connections on port 7734?
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/usr/local/bin/dbmigrate", line 9, in <module>
    load_entry_point('sm-dbmigration==1.0.1', 'console_scripts', 'dbmigrate')()
  File "/usr/local/lib/python3.4/dist-packages/dbmigration-1.0.1-py3.4.egg/dbmigration/dbmigrate.py", line 31, in main
    run_migration(sys.argv[1:])
  File "/usr/local/lib/python3.4/dist-packages/dbmigration-1.0.1-py3.4.egg/dbmigration/dbmigrate.py", line 26, in run_migration
    command.upgrade(alembic_cfg, "head")
  File "/usr/local/lib/python3.4/dist-packages/alembic-0.9.6-py3.4.egg/alembic/command.py", line 254, in upgrade
    script.run_env()
  File "/usr/local/lib/python3.4/dist-packages/alembic-0.9.6-py3.4.egg/alembic/script/base.py", line 425, in run_env
    util.load_python_file(self.dir, 'env.py')
  File "/usr/local/lib/python3.4/dist-packages/alembic-0.9.6-py3.4.egg/alembic/util/pyfiles.py", line 81, in load_python_file
    module = load_module_py(module_id, path)
  File "/usr/local/lib/python3.4/dist-packages/alembic-0.9.6-py3.4.egg/alembic/util/compat.py", line 97, in load_module_py
    module_id, path).load_module(module_id)
  File "<frozen importlib._bootstrap>", line 539, in _check_name_wrapper
  File "<frozen importlib._bootstrap>", line 1614, in load_module
  File "<frozen importlib._bootstrap>", line 596, in _load_module_shim
  File "<frozen importlib._bootstrap>", line 1220, in load
  File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1129, in _exec
  File "<frozen importlib._bootstrap>", line 1471, in exec_module
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
  File "/usr/local/lib/python3.4/dist-packages/dbmigration-1.0.1-py3.4.egg/dbmigration/alembic/env.py", line 70, in <module>
    run_migrations_online()
  File "/usr/local/lib/python3.4/dist-packages/dbmigration-1.0.1-py3.4.egg/dbmigration/alembic/env.py", line 58, in run_migrations_online
    with connectable.connect() as connection:
  File "/usr/local/lib/python3.4/dist-packages/SQLAlchemy-1.2.0b3-py3.4-linux-x86_64.egg/sqlalchemy/engine/base.py", line 2102, in connect
    return self._connection_cls(self, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/SQLAlchemy-1.2.0b3-py3.4-linux-x86_64.egg/sqlalchemy/engine/base.py", line 90, in __init__
    if connection is not None else engine.raw_connection()
  File "/usr/local/lib/python3.4/dist-packages/SQLAlchemy-1.2.0b3-py3.4-linux-x86_64.egg/sqlalchemy/engine/base.py", line 2188, in raw_connection
    self.pool.unique_connection, _connection)
  File "/usr/local/lib/python3.4/dist-packages/SQLAlchemy-1.2.0b3-py3.4-linux-x86_64.egg/sqlalchemy/engine/base.py", line 2162, in _wrap_pool_connect
    e, dialect, self)
  File "/usr/local/lib/python3.4/dist-packages/SQLAlchemy-1.2.0b3-py3.4-linux-x86_64.egg/sqlalchemy/engine/base.py", line 1476, in _handle_dbapi_exception_noconnection
    exc_info
  File "/usr/local/lib/python3.4/dist-packages/SQLAlchemy-1.2.0b3-py3.4-linux-x86_64.egg/sqlalchemy/util/compat.py", line 203, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/usr/local/lib/python3.4/dist-packages/SQLAlchemy-1.2.0b3-py3.4-linux-x86_64.egg/sqlalchemy/util/compat.py", line 186, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.4/dist-packages/SQLAlchemy-1.2.0b3-py3.4-linux-x86_64.egg/sqlalchemy/engine/base.py", line 2158, in _wrap_pool_connect
    return fn()
  File "/usr/local/lib/python3.4/dist-packages/SQLAlchemy-1.2.0b3-py3.4-linux-x86_64.egg/sqlalchemy/pool.py", line 344, in unique_connection
    return _ConnectionFairy._checkout(self)
  File "/usr/local/lib/python3.4/dist-packages/SQLAlchemy-1.2.0b3-py3.4-linux-x86_64.egg/sqlalchemy/pool.py", line 781, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/usr/local/lib/python3.4/dist-packages/SQLAlchemy-1.2.0b3-py3.4-linux-x86_64.egg/sqlalchemy/pool.py", line 531, in checkout
    rec = pool._do_get()
  File "/usr/local/lib/python3.4/dist-packages/SQLAlchemy-1.2.0b3-py3.4-linux-x86_64.egg/sqlalchemy/pool.py", line 1276, in _do_get
    return self._create_connection()
  File "/usr/local/lib/python3.4/dist-packages/SQLAlchemy-1.2.0b3-py3.4-linux-x86_64.egg/sqlalchemy/pool.py", line 349, in _create_connection
    return _ConnectionRecord(self)
  File "/usr/local/lib/python3.4/dist-packages/SQLAlchemy-1.2.0b3-py3.4-linux-x86_64.egg/sqlalchemy/pool.py", line 476, in __init__
    self.__connect(first_connect_check=True)
  File "/usr/local/lib/python3.4/dist-packages/SQLAlchemy-1.2.0b3-py3.4-linux-x86_64.egg/sqlalchemy/pool.py", line 666, in __connect
    connection = pool._invoke_creator(self)
  File "/usr/local/lib/python3.4/dist-packages/SQLAlchemy-1.2.0b3-py3.4-linux-x86_64.egg/sqlalchemy/engine/strategies.py", line 105, in connect
    return dialect.connect(*cargs, **cparams)
  File "/usr/local/lib/python3.4/dist-packages/SQLAlchemy-1.2.0b3-py3.4-linux-x86_64.egg/sqlalchemy/engine/default.py", line 410, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/usr/local/lib/python3.4/dist-packages/psycopg2-2.7.3.2-py3.4-linux-x86_64.egg/psycopg2/__init__.py", line 130, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) could not connect to server: Connection refused
  Is the server running on host "localhost" (127.0.0.1) and accepting
  TCP/IP connections on port 7734?
could not connect to server: Cannot assign requested address
  Is the server running on host "localhost" (::1) and accepting
  TCP/IP connections on port 7734?
```

**Comment by yosifkit** [comment]
Correct, the database on listens on the linux socket. Which is how postgres interprets `localhost`.

https://github.com/docker-library/postgres/blob/4566cb036dd021c42c252f7a41797d5d3907c0d2/docker-entrypoint.sh#L97-L99

**Comment by synthecypher** [comment]
@yosifkit is there anyway to change that behaviour so I can run my migration scripts as part of `initdb.d`?

**Comment by synthecypher** [comment]
For anyone else having this problem I solved it by using the default port in `initdb.d` scripts. Which is `5432`.
