### ISSUE TITLE
Unable to connect externally with 9.5.10-1.pgdg80+1

### ISSUE THREAD

**Issue by rbanikaz** [docker-library/postgres#369]
After pulling latest image from this repo where PG_VERSION=9.5.10-1.pgdg80+1 we see the following exception when trying to connect externally through SQLWorkbench:
```
2017-11-10 16:12:35 ERROR SQL Exception when connecting The connection attempt failed.
java.sql.SQLException: The connection attempt failed.
    at workbench.db.DbDriver.connect(DbDriver.java:548)
    at workbench.db.ConnectionMgr.connect(ConnectionMgr.java:255)
    at workbench.db.ConnectionMgr.getConnection(ConnectionMgr.java:182)
    at workbench.gui.components.ConnectionSelector.doConnect(ConnectionSelector.java:227)
    at workbench.gui.components.ConnectionSelector$1.run(ConnectionSelector.java:131)
Caused by: org.postgresql.util.PSQLException: The connection attempt failed.
    at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:275)
    at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:49)
    at org.postgresql.jdbc.PgConnection.<init>(PgConnection.java:194)
    at org.postgresql.Driver.makeConnection(Driver.java:450)
    at org.postgresql.Driver.connect(Driver.java:252)
    at workbench.db.DbDriver.connect(DbDriver.java:511)
    ... 4 more
Caused by: java.io.EOFException
    at org.postgresql.core.PGStream.receiveChar(PGStream.java:290)
    at org.postgresql.core.v3.ConnectionFactoryImpl.doAuthentication(ConnectionFactoryImpl.java:418)
    at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:222)
    ... 9 more
```

This worked just fine when PG_VERSION=9.5.9-1.pgdg80+1

Additionally we are unable to connect using the `psql` client:
```
➜  rocket git:(dockerize-postgres) PGPASSWORD=postgres psql -h localhost -p 5432 -d dwenigma -U postgres --no-password
psql: server closed the connection unexpectedly
	This probably means the server terminated abnormally
	before or while processing the request.
➜  rocket git:(dockerize-postgres)
```

This was also working fine with the older version...  Any ideas why this is happening?

**Comment by yosifkit** [comment]
How are you running postgres (ie what does your `docker run` or `docker-compose.yml` look like)?

We run a connection test on every version bump using scripts in the [docker-library/official-images](https://github.com/docker-library/official-images/tree/f2f2857c7336d80953175fdcff7b5f5c6f0402dc/test). See the most recent TravisCI test [here](https://travis-ci.org/docker-library/postgres/jobs/299826296#L1592-L1598).  I also ran a container locally and was able to connect with psql in another container. 

See, [postgres-basics](https://github.com/docker-library/official-images/blob/f2f2857c7336d80953175fdcff7b5f5c6f0402dc/test/tests/postgres-basics/run.sh) and [postgres-initdb](https://github.com/docker-library/official-images/blob/f2f2857c7336d80953175fdcff7b5f5c6f0402dc/test/tests/postgres-initdb/run.sh) for the specifics of the tests.

**Comment by ahanoff** [comment]
I am getting ```server closed the connection unexpectedly``` error while trying to connect to postgres container using pgadmin. I tried both, new pgadmin4 container version and desktop version as well, both return me same error.

Postgres container were running using ```docker run``` and ```docker-compose```, I had no changes to docker-compose file, and it was working couple weeks ago. 

I do port exposing to host machine.
