### ISSUE TITLE
debian buster (raspbi): seg fault on starting w/ existing db cluster/dir

### ISSUE THREAD

**Issue by vobu** [docker-library/postgres#830]
## description

`postgres` segfaults when started with an existing `datadir` mounted as a a volume, even with 
- `--security-opt seccomp:unconfined`
- latest `libseccom`(`libseccomp2:armhf 2.5.1-1`), see #812 
- `swap` all fine

```bash
$ docker run -it -v /home/pi/docker-volumes/postgresql/data:/var/lib/postgresql/data --rm --platform linux/arm/v7 --name db-test --env-file db.env --security-opt seccomp:unconfined postgres:alpine

PostgreSQL Database directory appears to contain a database; Skipping initialization

LOG:  starting PostgreSQL 13.2 on arm-unknown-linux-musleabihf, compiled by gcc (Alpine 10.2.1_pre1) 10.2.1 20201203, 32-bit
LOG:  listening on IPv4 address "0.0.0.0", port 5432
LOG:  listening on IPv6 address "::", port 5432
LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
LOG:  startup process (PID 22) was terminated by signal 11: Segmentation fault
LOG:  aborting startup due to startup process failure
LOG:  database system is shut down
```
(-> more extensive log output and context at the end)

note: it works fine on an empty/new `datadir` (note the `-v` mapping)!

```bash
docker run -it -v /home/pi/docker-volumes/postgresql/data-clean:/var/lib/postgresql/data --rm --platform linux/arm/v7 --name db-test --env-file db.env --security-opt seccomp:unconfined postgres:alpine
The files belonging to this database system will be owned by user "postgres".
This user must also own the server process.

The database cluster will be initialized with locale "en_US.utf8".
The default database encoding has accordingly been set to "UTF8".
The default text search configuration will be set to "english".

Data page checksums are disabled.

fixing permissions on existing directory /var/lib/postgresql/data ... ok
creating subdirectories ... ok
selecting dynamic shared memory implementation ... posix
selecting default max_connections ... 100
selecting default shared_buffers ... 128MB
selecting default time zone ... UTC
creating configuration files ... ok
running bootstrap script ... ok
performing post-bootstrap initialization ... sh: locale: not found
2021-04-06 21:34:31.308 UTC [32] WARNING:  no usable system locales were found
ok
syncing data to disk ... ok

initdb: warning: enabling "trust" authentication for local connections
You can change this by editing pg_hba.conf or using the option -A, or
--auth-local and --auth-host, the next time you run initdb.

Success. You can now start the database server using:

    pg_ctl -D /var/lib/postgresql/data -l logfile start

waiting for server to start....2021-04-06 21:34:35.021 UTC [37] LOG:  starting PostgreSQL 13.2 on arm-unknown-linux-musleabihf, compiled by gcc (Alpine 10.2.1_pre1) 10.2.1 20201203, 32-bit
2021-04-06 21:34:35.043 UTC [37] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
2021-04-06 21:34:35.058 UTC [38] LOG:  database system was shut down at 2021-04-06 21:34:33 UTC
2021-04-06 21:34:35.068 UTC [37] LOG:  database system is ready to accept connections
 done
server started
CREATE DATABASE


/usr/local/bin/docker-entrypoint.sh: ignoring /docker-entrypoint-initdb.d/*

waiting for server to shut down...2021-04-06 21:34:35.664 UTC [37] LOG:  received fast shutdown request
.2021-04-06 21:34:35.668 UTC [37] LOG:  aborting any active transactions
2021-04-06 21:34:35.672 UTC [37] LOG:  background worker "logical replication launcher" (PID 44) exited with exit code 1
2021-04-06 21:34:35.673 UTC [39] LOG:  shutting down
2021-04-06 21:34:35.724 UTC [37] LOG:  database system is shut down
 done
server stopped

PostgreSQL init process complete; ready for start up.

2021-04-06 21:34:35.864 UTC [1] LOG:  starting PostgreSQL 13.2 on arm-unknown-linux-musleabihf, compiled by gcc (Alpine 10.2.1_pre1) 10.2.1 20201203, 32-bit
2021-04-06 21:34:35.864 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
2021-04-06 21:34:35.864 UTC [1] LOG:  listening on IPv6 address "::", port 5432
2021-04-06 21:34:35.875 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
2021-04-06 21:34:35.891 UTC [51] LOG:  database system was shut down at 2021-04-06 21:34:35 UTC
2021-04-06 21:34:35.901 UTC [1] LOG:  database system is ready to accept connections
```
## environment
- Raspberry Pi 4 Model B Rev 1.2 (4GB RAM)
- Raspbian GNU/Linux 10.9 (buster)
- `$ uname -a`   
  `Linux raspberrypi 5.10.17-v7l+ #1403 SMP Mon Feb 22 11:33:35 GMT 2021 armv7l GNU/Linux`
- `$ docker -v`
  `Docker version 20.10.5, build 55c4c88`
- `$ dpkg -l libseccomp2`
  `ii  libseccomp2:armhf 2.5.1-1      armhf        high level interface to Linux seccomp filter`

## additional debugging
```
# started a container straight into bash instead of the pg init
docker run -it -v /home/pi/docker-volumes/postgresql/data:/var/lib/postgresql/data --rm --platform linux/arm/v7 --name db-test --env-file db.env --security-opt seccomp:unconfined --entrypoint "/bin/bash" postgres:alpine

# then, inside the container, became postgres and tried to start things manually:
bash-5.1$ id
uid=70(postgres) gid=70(postgres) groups=70(postgres),70(postgres)

bash-5.1$ /usr/local/bin/postgres -d 5
DEBUG:  postgres: PostmasterMain: initial environment dump:
DEBUG:  -----------------------------------------
DEBUG:  	SHELL=/bin/sh
DEBUG:  	HOSTNAME=5d6ea65d1d61
DEBUG:  	POSTGRES_PASSWORD=<snip>
DEBUG:  	PWD=/var/lib/postgresql/data
DEBUG:  	LOGNAME=postgres
DEBUG:  	PG_SHA256=5fd7fcd08db86f5b2aed28fcfaf9ae0aca8e9428561ac547764c2a2b0f41adfc
DEBUG:  	HOME=/var/lib/postgresql
DEBUG:  	LANG=en_US.utf8
DEBUG:  	PG_MAJOR=13
DEBUG:  	PG_VERSION=13.2
DEBUG:  	TERM=xterm
DEBUG:  	USER=postgres
DEBUG:  	SHLVL=3
DEBUG:  	POSTGRES_USER=<snip>
DEBUG:  	PGDATA=/var/lib/postgresql/data
DEBUG:  	PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
DEBUG:  	POSTGRES_DB=<snip>
DEBUG:  	OLDPWD=/var/lib/postgresql
DEBUG:  	_=/usr/local/bin/postgres
DEBUG:  	PGSYSCONFDIR=/usr/local/etc/postgresql
DEBUG:  	LC_COLLATE=en_US.utf8
DEBUG:  	LC_CTYPE=en_US.utf8
DEBUG:  	LC_MESSAGES=en_US.utf8
DEBUG:  	LC_MONETARY=C
DEBUG:  	LC_NUMERIC=C
DEBUG:  	LC_TIME=C
DEBUG:  -----------------------------------------
DEBUG:  using armv8 crc32 hardware = 1
DEBUG:  registering background worker "logical replication launcher"
DEBUG:  invoking IpcMemoryCreate(size=146718720)
DEBUG:  mmap(146800640) with MAP_HUGETLB failed, huge pages disabled: Invalid argument
DEBUG:  dynamic shared memory system will support 674 segments
DEBUG:  created dynamic shared memory control segment 1964770447 (10796 bytes)
DEBUG:  max_safe_fds = 987, usable_fds = 1000, already_open = 3
LOG:  starting PostgreSQL 13.2 on arm-unknown-linux-musleabihf, compiled by gcc (Alpine 10.2.1_pre1) 10.2.1 20201203, 32-bit
LOG:  listening on IPv4 address "0.0.0.0", port 5432
LOG:  listening on IPv6 address "::", port 5432
LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
DEBUG:  reaping dead processes
LOG:  startup process (PID 70) was terminated by signal 11: Segmentation fault
LOG:  aborting startup due to startup process failure
DEBUG:  shmem_exit(1): 0 before_shmem_exit callbacks to make
DEBUG:  shmem_exit(1): 5 on_shmem_exit callbacks to make
DEBUG:  cleaning up dynamic shared memory control segment with ID 1964770447
DEBUG:  proc_exit(1): 2 callbacks to make
LOG:  database system is shut down
DEBUG:  exit(1)
DEBUG:  shmem_exit(-1): 0 before_shmem_exit callbacks to make
DEBUG:  shmem_exit(-1): 0 on_shmem_exit callbacks to make
DEBUG:  proc_exit(-1): 0 callbacks to make

```

**Comment by tianon** [comment]
Interesting!  Do you get similar results with `--platform linux/arm/v6 postgres:alpine` and/or `--platform linux/arm/v7 postgres:latest`?

**Comment by vobu** [comment]
### `arm/v6` 😞 
```bash
$ docker run -it -v /home/pi/docker-volumes/postgresql/data:/var/lib/postgresql/data --rm --platform linux/arm/v6 --name db-test --env-file db.env --security-opt seccomp:unconfined postgres:alpine

PostgreSQL Database directory appears to contain a database; Skipping initialization

LOG:  starting PostgreSQL 13.2 on arm-unknown-linux-musleabihf, compiled by gcc (Alpine 10.2.1_pre1) 10.2.1 20201203, 32-bit
LOG:  listening on IPv4 address "0.0.0.0", port 5432
LOG:  listening on IPv6 address "::", port 5432
LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
LOG:  startup process (PID 21) was terminated by signal 11: Segmentation fault
LOG:  aborting startup due to startup process failure
2021-04-07 07:18:20.043 UTC [1] LOG:  database system is shut down
```

### `postgres:latest` 😞 
```bash
$ docker run -it -v /home/pi/docker-volumes/postgresql/data:/var/lib/postgresql/data --rm --platform linux/arm/v7 --name db-test --env-file db.env --security-opt seccomp:unconfined postgres:latest
Unable to find image 'postgres:latest' locally
latest: Pulling from library/postgres
# ...
PostgreSQL Database directory appears to contain a database; Skipping initialization

LOG:  starting PostgreSQL 13.2 (Debian 13.2-1.pgdg100+1) on arm-unknown-linux-gnueabihf, compiled by gcc (Debian 8.3.0-6) 8.3.0, 32-bit
LOG:  listening on IPv4 address "0.0.0.0", port 5432
LOG:  listening on IPv6 address "::", port 5432
LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
LOG:  startup process (PID 27) was terminated by signal 11: Segmentation fault
LOG:  aborting startup due to startup process failure
LOG:  database system is shut down
```

(yes, also tried with `v6` and `postgres:latest`, same segfault)

**Comment by vobu** [comment]
some further investigation: here's what's really killing me:
if started up with an empty `datadir`, all good (even w/o `--security-opt seccomp:unconfined`)
```bash
$ sudo rm -rf /home/pi/docker-volumes/postgresql/data-new
$ docker run -it -v /home/pi/docker-volumes/postgresql/data-new:/var/lib/postgresql/data --rm --platform linux/arm/v7 --name db-test --env-file db.env postgres:alpine
# ...
The database cluster will be initialized with locale "en_US.utf8".
The default database encoding has accordingly been set to "UTF8".
The default text search configuration will be set to "english".
# ...
LOG:  database system is ready to accept connections
```

re-starting the container w/ the previously initialized db: also **_all good_** 😲 😱 !
```bash
$ docker run -it -v /home/pi/docker-volumes/postgresql/data-new:/var/lib/postgresql/data --rm --platform linux/arm/v7 --name db-test --env-file db.env postgres:alpine

PostgreSQL Database directory appears to contain a database; Skipping initialization

LOG:  starting PostgreSQL 13.2 on arm-unknown-linux-musleabihf, compiled by gcc (Alpine 10.2.1_pre1) 10.2.1 20201203, 32-bit
LOG:  listening on IPv4 address "0.0.0.0", port 5432
LOG:  listening on IPv6 address "::", port 5432
LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
LOG:  database system was shut down at 2021-04-07 08:59:07 UTC
LOG:  database system is ready to accept connections
```

re-starting the same container w/ `datadir` from a previous Postgres 13 image: no good 😕 
(was also `postgres:alpine`, can't retro-find out the exact version/image, but for sure already 13)
```bash
$ docker run -it -v /home/pi/docker-volumes/postgresql/data:/var/lib/postgresql/data --rm --platform linux/arm/v7 --name db-test --env-file db.env postgres:alpine

PostgreSQL Database directory appears to contain a database; Skipping initialization

LOG:  starting PostgreSQL 13.2 on arm-unknown-linux-musleabihf, compiled by gcc (Alpine 10.2.1_pre1) 10.2.1 20201203, 32-bit
LOG:  listening on IPv4 address "0.0.0.0", port 5432
LOG:  listening on IPv6 address "::", port 5432
LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
LOG:  startup process (PID 23) was terminated by signal 11: Segmentation fault
LOG:  aborting startup due to startup process failure
LOG:  database system is shut down
```

**-> so it clearly must be an issue w/ the `datadir` itself.**

given that this was a bare-bones, un-customized postgres container running and used "as-is", I'm out of hunches.

Here's a `tree` snippet of `datadir`, probably someone can spot something 😬 :
```
.
├── base
│   ├── 1
│   │   ├── 112
│   │   ├── 113
│   │   ├── 1247
│   │   ├── 1247_fsm
│   │   ├── 1247_vm
│   │   ├── 1249
│   │   ├── 1249_fsm
│   │   ├── 1249_vm
...
│   │   ├── 828
│   │   ├── pg_filenode.map
│   │   └── PG_VERSION
│   ├── 13441
│   │   ├── 112
│   │   ├── 113
│   │   ├── 1247
│   │   ├── 1247_fsm
│   │   ├── 1247_vm
...
│       ├── pg_filenode.map
│       ├── pg_internal.init
│       └── PG_VERSION
├── core
├── global
│   ├── 1213
│   ├── 1213_fsm
│   ├── 1213_vm
│   ├── 1214
│   ├── 1214_fsm
│   ├── 1214_vm
...
│   ├── pg_control
│   ├── pg_filenode.map
│   └── pg_internal.init
├── pg_commit_ts
├── pg_dynshmem
├── pg_hba.conf
├── pg_ident.conf
├── pg_logical
│   ├── mappings
│   ├── replorigin_checkpoint
│   └── snapshots
├── pg_multixact
│   ├── members
│   │   └── 0000
│   └── offsets
│       └── 0000
├── pg_notify
├── pg_replslot
├── pg_serial
├── pg_snapshots
├── pg_stat
├── pg_stat_tmp
├── pg_subtrans
│   └── 0010
├── pg_tblspc
├── pg_twophase
├── PG_VERSION
├── pg_wal
│   ├── 00000001000000000000004C
│   ├── 00000001000000000000004D
│   ├── 00000001000000000000004E
│   ├── 00000001000000000000004F
│   ├── 000000010000000000000050
│   └── archive_status
├── pg_xact
│   ├── 0000
│   └── 0001
├── postgresql.auto.conf
├── postgresql.conf
└── postmaster.opts
```

**Comment by mielune** [comment]
Same trouble here. I tried with all available images for armv7, pgsql v12 :(
Unable to restart my project with its existing db folder.

**Comment by yosifkit** [comment]
I tried to reproduce locally by initializing a data directory with each of `12.0` through `12.5` (both Debian and Alpine based), stopping and deleting the container, and then running `12.6` (Debian and Alpine based) with that data directory and none of them failed. All images were freshly pulled `arm32v7/postgres:12.X[-alpine]`.

(tested on a Packet ARM server)

---

Does the data directory work with the original image that was running? Maybe the data directory got corrupted?

----

Have you been able to narrow it down to which version of the image that created the initial directory and if the image was upgraded along the way?

Since images are also rebuilt when base images are updated, there could be something other than the PostgreSQL version affecting the image. So, if you want to go deeper, the git history of `docker-library/repo-info` [postgres/remote/12.md](https://github.com/docker-library/repo-info/blob/f8a73e9380c80ca7a0b1f13f318218399e3a21c4/repos/postgres/remote/12.md) can give your more granularity with every sha256 image hash pushed to docker hub as `postgres:12`

**Comment by mielune** [comment]
@yosifkit  Thank you for your tips about the repo-info :)

I lost the origninal image due the the same tag is used (12-alpine)

So I look into the commit history for the 12-alpine.md file and go back to an older release for arm v7.
Tried with hash from old commits: 
- 2020-12-30: failed postgres@sha256:54fddcfa4ab57116b88fc96e876f61f7e40063426f43d48c60f5f370b3a9505c 
- 2020-11-13: failed postgres@sha256:55167d6e5bc66977cb67710a27809355801edbac705b29a584b9c721097b2e5a
- 2020-01-23: failed postgres@sha256:3979cf540f20cf7db6713f8ecc0da8e2c684832af8e97d1544e6497b381cf26a

So this is not a bug of the Postgres image, this logs are from the last one (12.1):
```
2021-04-14 14:49:04.388 UTC [1] LOG:  starting PostgreSQL 12.1 on arm-unknown-linux-musleabihf, compiled by gcc (Alpine 8.3.0) 8.3.0, 32-bit
2021-04-14 14:49:04.391 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
2021-04-14 14:49:04.391 UTC [1] LOG:  listening on IPv6 address "::", port 5432
2021-04-14 14:49:05.050 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
2021-04-14 14:49:20.998 UTC [1] LOG:  startup process (PID 13) was terminated by signal 11: Segmentation fault
2021-04-14 14:49:20.998 UTC [1] LOG:  aborting startup due to startup process failure
2021-04-14 14:49:21.167 UTC [1] LOG:  database system is shut down
```

Based on 
- Docker 20.10.5
- RasperryPI v3 (armv7l)
- Raspbian 32b
- Linux kernel 5.10.17-v7+ #1403

I have no more ideas how to further investigate on this issue.

**Comment by mielune** [comment]
Found some pointer about a similar problem here : https://github.com/timescale/timescaledb/issues/2968

Last Raspbian upgrade use this version: libseccomp2/stable,now 2.3.3-4 armhf [installed]

Starting the lastest  container have date troubles:
```sh
docker run -it  arm32v7/postgres:12-alpine sh
/ # apk update
fetch https://dl-cdn.alpinelinux.org/alpine/v3.13/main/armv7/APKINDEX.tar.gz
ERROR: https://dl-cdn.alpinelinux.org/alpine/v3.13/main: temporary error (try again later)
WARNING: Ignoring https://dl-cdn.alpinelinux.org/alpine/v3.13/main: No such file or directory
fetch https://dl-cdn.alpinelinux.org/alpine/v3.13/community/armv7/APKINDEX.tar.gz
ERROR: https://dl-cdn.alpinelinux.org/alpine/v3.13/community: temporary error (try again later)
WARNING: Ignoring https://dl-cdn.alpinelinux.org/alpine/v3.13/community: No such file or directory
2 errors; 33 distinct packages available
/ # ^C
/ # date
Sun Jan  0 00:100:4174038  1900
```

So try with a debian based from 20/11/13: ok with  an empty db but ko with an existing one.

```
PostgreSQL Database directory appears to contain a database; Skipping initialization

2021-04-14 16:23:43.367 UTC [1] LOG:  starting PostgreSQL 12.6 (Debian 12.6-1.pgdg100+1) on arm-unknown-linux-gnueabihf, compiled by gcc (Debian 8.3.0-6) 8.3.0, 32-bit
2021-04-14 16:23:43.369 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
2021-04-14 16:23:43.369 UTC [1] LOG:  listening on IPv6 address "::", port 5432
2021-04-14 16:23:43.537 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
2021-04-14 16:24:01.154 UTC [1] LOG:  startup process (PID 14) was terminated by signal 11: Segmentation fault
2021-04-14 16:24:01.154 UTC [1] LOG:  aborting startup due to startup process failure
2021-04-14 16:24:01.314 UTC [1] LOG:  database system is shut down
```

We have two troubles:
- alpine builds have a datetime problem
- debian based have a segfault if a db already exists

**Comment by mielune** [comment]
Searching by, I did more investigations :

- build postgres from sources in the RPi v3
- ran postgres with the existing db --> segfault :/
- I enabled coredump to get one and tryed to use gdb to get debug infos but I don't know how to use it. 

I can send the codedump if someone can help :)

**Comment by mielune** [comment]
I built postgres 12.6 with debugmode and restart in Pi3.
Coredump backtrace displayed:

```
[New LWP 18607]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/arm-linux-gnueabihf/libthread_db.so.1".
Core was generated by `postgres: startup                                    '.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x006ee1e4 in _fmt (format=0x716755 "Y-%m-%d %H:%M:%S %Z", t=0x0, pt=0x8be174 <buf> "", 
    ptlim=0x8be1f4 <already_done> "", warnp=0x7eadd604) at strftime.c:450
450						pt = _yconv(t->tm_year, TM_YEAR_BASE,
(gdb) backtrace
#0  0x006ee1e4 in _fmt (format=0x716755 "Y-%m-%d %H:%M:%S %Z", t=0x0, pt=0x8be174 <buf> "", 
    ptlim=0x8be1f4 <already_done> "", warnp=0x7eadd604) at strftime.c:450
#1  0x006ed27c in pg_strftime (s=0x8be174 <buf> "", maxsize=128, format=0x716754 "%Y-%m-%d %H:%M:%S %Z", t=0x0)
    at strftime.c:134
#2  0x0014f564 in str_time (tnow=9144330001359831040) at xlog.c:5321
#3  0x001515b8 in StartupXLOG () at xlog.c:6278
#4  0x0043e834 in StartupProcessMain () at startup.c:226
#5  0x0016b69c in AuxiliaryProcessMain (argc=2, argv=0x7eade12c) at bootstrap.c:451
#6  0x0043d324 in StartChildProcess (type=StartupProcess) at postmaster.c:5472
#7  0x004376d8 in PostmasterMain (argc=3, argv=0xb2be30) at postmaster.c:1390
#8  0x0034ecc8 in main (argc=3, argv=0xb2be30) at main.c:228
(gdb) 
```

Postgres start logs:
```
2021-04-22 17:53:57.351 UTC [18606] LOG:  starting PostgreSQL 12.6 on armv7l-unknown-linux-gnueabihf, compiled by gcc (Raspbian 8.3.0-6+rpi1) 8.3.0, 32-bit
2021-04-22 17:53:57.353 UTC [18606] LOG:  listening on IPv4 address "0.0.0.0", port 5432
2021-04-22 17:53:57.353 UTC [18606] LOG:  listening on IPv6 address "::", port 5432
2021-04-22 17:53:57.392 UTC [18606] LOG:  listening on Unix socket "/tmp/.s.PGSQL.5432"
2021-04-22 17:54:10.227 UTC [18606] LOG:  startup process (PID 18607) was terminated by signal 11: Erreur de segmentation
2021-04-22 17:54:10.228 UTC [18606] LOG:  aborting startup due to startup process failure
2021-04-22 17:54:10.338 UTC [18606] LOG:  database system is shut down

```

I this can help :)

**Comment by vobu** [comment]
@mielune thanks for all your investigations. i admire your perseverance!
(also still having the issue, but haven't had enough time to cater to it)
